baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'unofficial docs'

[[module.imports]]
path = "github.com/imfing/hextra"

[[menu.main]]
name = "Kobo official"
url = "https://help.kobo.com/hc/en-us/articles/360019123773-Kobo-eReader-User-Guide"
weight = 1

[[menu.main]]
name = "KOReader repo"
url = "https://github.com/koreader/koreader" 
weight = 2

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/littlepriests/kobo-beginner"

  [menu.main.params]
  icon = "github"

[params.navbar]
displayTitle = true
displayLogo = true

  [params.navbar.logo]
  path = "logo.png"
  link = "/"
  width = 40
  height = 20

[params.page]
width = "wide"

[params.search]
enable = true
type = "flexsearch"

  [params.search.flexsearch]
  index = "content"
